### ISSUE TITLE
[SUGGESTION] Default commands to the sender name

### ISSUE THREAD

**Issue by vaniron** [Krripe/BlanketEconomy#3]
Hi, could you please default commands so that without argument used they will target the sender?
So players can use for example "/beco balance" without any nickname to show their own balance.
Main reason is i can then make aliases for those commands and not care about arguments.

**Comment by Krripe** [comment]
**Discord**
https://discord.gg/nrENPTmQKt



Allows players to view their own balance with the /beco balance command.

```blanketeconomy.balance```

Allows players to view other players' balances with the /beco balance [player] command.

```blanketeconomy.balance.others```

Grants access to view the top balances with the /beco top command.

```blanketeconomy.top```

**Comment by Krripe** [comment]
/eco balance is to see your own balance
/eco balance <player> it's to see the balance from another player
https://discord.gg/nrENPTmQKt

**Comment by Krripe** [comment]
are you using the version on github?

**Comment by vaniron** [comment]
I redownloaded correct version from modrinth and its okay. Sorry.

Would it be possible to add check for offline players?

**Comment by Krripe** [comment]
I suggest you join on discord to see what i'm working on for the next updates and other projects
