### ISSUE TITLE
Mod will not work in 1.21.4

### ISSUE THREAD

**Issue by Schnullie** [Krripe/BlanketEconomy#4]
Mod does not work on 1.21.4, even though it specified it should work on 1.21.4.

I used BlanketEconomy ver. 1.4.3 on fabric-loader-0.16.9 with Minecraft ver. 1.21.4

Server Error: Mod 'BlanketEconomy' (blanketeconomy) 1.4 requires version 1.21, version 1.21.1, version 1.21.2 or version 1.21.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.4!

Either Update the Mod or the Description on Modrinth

**Comment by Krripe** [comment]
I'm sorry, i haven't added support for minecraft 1.21.4 yet, unfortunately, now i noticed that Modrinth has changed what i set to versions, the mod only works on minecraft 1.21-1.21.3

**Comment by Schnullie** [comment]
Thank you
